url: https://zapaz.github.io/kredeum
baseurl: /kredeum/

# Site settings
title:Kredeum
email: alain.papazoglou@kredeum.com
description: "Kredeum - Architectes blockchain"

# Team names, titles and social links
people:
- name: Yoann Lesouef
  pic: 1
  position: Co-fondateur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alexandre Rouillet
  pic: 2
  position: Co-fondateur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Alain Papazoglou
  pic: 3
  position: Co-fondateur
  social:
    - title: twitter
      url: #papaz
    - title: linkedin
      url: #alain

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kredeum
  - title: github
    url: http://github.com/kredeum

# Postal address (add as many lines as necessary)
address:
  - line: Au Thabor Coworking
  - line: 14 rue Waldeck Rousseau
  - line: 35700 Rennes

# Build settings
markdown: kramdown
permalink: pretty
